# Generated by Django 4.0.3 on 2022-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlumni',
            fields=[
                ('slNo', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=400)),
                ('eMail', models.CharField(max_length=50)),
            ],
        ),
    ]
